### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by c0debreaker** [LeoTindall/crackmes#8]
First of all, thank you for making the article.

I'm running `Linux debian 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux`

Here is the error. What am I missing?

```
root@debian:/usr/local/src/crackmes# make
gcc -O1 -fno-stack-protector -lcrypt -m64 crackme07.c -o crackme07.64
objcopy -N FILE crackme07.64
gcc -O1 -fno-stack-protector -lcrypt -m64 crackme01e.c -o crackme01e.64
objcopy -N FILE crackme01e.64
gcc -O1 -fno-stack-protector -lcrypt -m64 crackme05e.c -o crackme05e.64
crackme05e.c: In function ‘check_with_mod’:
crackme05e.c:17:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (int i = 0; i < n; i++) {
     ^
crackme05e.c:17:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
Makefile:14: recipe for target 'crackme05e.64' failed
make: *** [crackme05e.64] Error 1
```

**Comment by NoraCodes** [comment]
What's your GCC? Mine is `gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0` and does not fail.

**Comment by c0debreaker** [comment]
It worked fine on my Ubuntu that has gcc 5.4.0. However, the one I posted above was on Debian. The gcc version was 4.9.2. Thanks.
